### ISSUE TITLE
Mega-Linter-Runner --install errors out when attempting to install to a path containing spaces

### ISSUE THREAD

**Issue by CAM-Gerlach** [megalinter/megalinter#676]
**Describe the bug**

I attempted to use `mega-linter-install` via npx to set up my mega-linter configuration. However, running it fails, with an error that clearly seems to be due to my (10 year old) user account having spaces in its home directory name, since I didn't know any better at the time. Given I can only see the first portion of the path up until the first space, I cannot be sure if the specific path affected is the working dir, repo dir, the npm cache path or something else, but I assume the traceback will help you track it down. I can confirm running the identical version on the same commit from the same repo on one of my Linux machines without the space works fine.

Let me know if this needs to be reported upstream; I initially investigated to see if it was an issue with Yeoman, but I couldn't find anything, and at least on the surface it looked like the problem might be the generator named passed into Yeoman by something downstream, such as this package. Thanks!

**To Reproduce**

1. Login to a user account on Windows that has spaces in its name
2. Run `npx mega-linter-runner --install`
3. Error occurs

**Expected behavior**

mega-linter-runner to correctly handle paths, including those with spaces or other special characters, and particularly those that cannot be easily changed by the user (e.g. home dir name).

**Screenshots**

```traceback
C. A. M. Gerlach@QUASIMODO MINGW64 ~/Documents/dev/SpaceX/submanager (master)
$ npx mega-linter-runner --install
C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\yeoman-environment\lib\environment.js:630
        new Error(
        ^

Error: You don't seem to have a generator with the name “C:\Users\C.” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-C:\Users\C..

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at Environment.create (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\yeoman-environment\lib\environment.js:630:9)
    at instantiateAndRun (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\yeoman-environment\lib\environment.js:729:30)
    at Environment.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\yeoman-environment\lib\environment.js:758:12)
    at MegaLinterRunner.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\mega-linter-runner\lib\runner.js:43:11)
    at MegaLinterRunnerCli.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\mega-linter-runner\lib\cli.js:11:34)
    at C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\mega-linter-runner\lib\index.js:13:37
    at Object.<anonymous> (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\614e542633a698fb\node_modules\mega-linter-runner\lib\index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
```

**Additional context**

Tested on Windows 8.1 x64 with both npm 7.0.3 and 7.21.0 on Node 15.0.1, and `mega-linter-runner` 4.41.0, running on both Git Bash under ConEmu (i.e. Cmdr) and legacy Windows cmd.

**Comment by nvuillam** [comment]
I think a line of code didn't like your spaces :) 

```javascript
path.resolve(`${__dirname}/../generators/mega-linter\`)
```

I replaced it with the following, it should be better:

```javascript
      const generatorPath = path.resolve(
        path.join(__dirname, "..", "generators", "mega-linter")
      );
      console.log("Yeoman generator used: " + generatorPath);
```

Please can you confirm it's ok by trying again with beta version ?

```shell
npx mega-linter-runner@beta --install
```

Thanks :)

**Comment by CAM-Gerlach** [comment]
@nvuillam Sorry for the delay; I came down with what I believe was meningitus and was busy on other projects.

I ran the command as requested in the same directly as before, and received a similar though not identical traceback. Is there anything else that would be helpful for me to provide or test?

```python-traceback
C. A. M. Gerlach@QUASIMODO MINGW64 ~/Documents/dev/SpaceX/submanager (master)
$ npx mega-linter-runner@beta --install
Yeoman generator used: C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\generators\mega-linter
C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:747
        throw new Error(
              ^

Error: You don't seem to have a generator with the name “C:\Users\C.” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-C:\Users\C..

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at checkGenerator (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:747:15)
    at Environment.create (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:774:29)
    at instantiateAndRun (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:987:36)
    at Environment.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:1004:12)
    at MegaLinterRunner.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\runner.js:47:11)
    at MegaLinterRunnerCli.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\cli.js:11:34)
    at C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\index.js:13:37
    at Object.<anonymous> (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
```

**Comment by nvuillam** [comment]
I'm afraid it's a yeoman bug, it seems there is an issue because yeoman splits the generator path when there are spaces :/

I declared the bug, let's hope they solve it soon :)

Meanwhile... maybe you can try 

```
npm install -g mega-linter-runner
mega-linter-runner --install
```

https://github.com/yeoman/generator/issues/1314

**Comment by CAM-Gerlach** [comment]
@nvuillam Thanks. Is yeoman sort of like cookiecutter for JS? I couldn't find an existing issue on there and figured if it really was upstream someone would have run into it, but evidently not.

I was going to try a global install before but didn't want to mess with my system install. In any case, I went ahead and did so, and received the same error because the Windows `Program Files` directory also has a space in it. So anyone installing globally on Windows will run into this problem too.

```python-traceback
C. A. M. Gerlach@QUASIMODO MINGW64 ~/Documents/dev/SpaceX/submanager (update-cis-post-060)
$ mega-linter-runner --install
C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:630
        new Error(
        ^

Error: You don't seem to have a generator with the name “C:\Program” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-C:\Program.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at Environment.create (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:630:9)
    at instantiateAndRun (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:729:30)
    at Environment.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:758:12)
    at MegaLinterRunner.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\runner.js:43:11)
    at MegaLinterRunnerCli.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\cli.js:11:34)
    at C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\index.js:13:37
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
```

**Comment by nvuillam** [comment]
Yes, yeoman is like cookiecutter, it is very used in JS community :)

https://yeoman.io/

https://www.saashub.com/compare-yeoman-vs-cookiecutter

**Comment by nvuillam** [comment]
Meanwhile, anyone can still setup Mega-Linter in a few minutes by following the manual instructions :)

https://nvuillam.github.io/mega-linter/installation/#manual-installation

**Comment by CAM-Gerlach** [comment]
I just sshed into one of my Linux boxes, run it there and then synced the repo back, heh

**Comment by CAM-Gerlach** [comment]
> https://www.saashub.com/compare-yeoman-vs-cookiecutter

![image](https://user-images.githubusercontent.com/17051931/131231785-71f58b7b-e281-48eb-b0bf-163e676aa26b.png)

Hmmm, dunno how I feel about that one :joy:

**Comment by nvuillam** [comment]
I didn't fully read the article , it's probably some automatically generated website based on web scraping :D 

https://yeoman.io/generators/ show that numerous trendy projects have an associated yeoman generator ^^ 
I didn't know cookiecutter before you mention it.... so I think it's more about community habits ^^ ( Mega-Linter is my first experience in Python, but I am playing in JS/TS ecosystem for years ... maybe you are more a python guy ? :p )

**Comment by CAM-Gerlach** [comment]
> I didn't fully read the article , it's probably some automatically generated website based on crappy web scraping :D

Yeah, I'm generally pretty skeptical of such things and don't find them all that useful in general, and prefer a variety of actual user/dev opinions as well as comparing documentation and usage numbers :smile: 

> maybe you are more a python guy ? :p )

Yeah, I am. It rather surprised me that you weren't, since you re-wrote super linter in Python after all. 

> According to github stars, cookiecutter (15k stars) seems more liked that yeoman (10k stars ^^ ) rofl

Where's the yeoman repo? All I could find were yeoman/yo with 3k and yeoman/generator and a few others with 1k. And yeah, a lot of the most popular cookiecutter templates have 3k-8k stars by themselves, heh.

**Comment by nvuillam** [comment]
> Yeah, I am. It rather surprised me that you weren't, since you re-wrote super linter in Python after all.

I don't have any religion... I used to use javascript / typescript or java / groovy for a while, and while I was thinking about which language to use to recode the messy bash of super-linter, I decided it was the time to see if python deserved all the hype I heard about and use mega-linter as my "hello world" in python  :)
I don't regret it, that's such an elegant language :)

> Where's the yeoman repo? All I could find were yeoman/yo with 3k and yeoman/generator and a few others with 1k. And yeah, a lot of the most popular cookiecutter templates have 3k-8k stars by themselves, heh.

yeoman/yeoman :)

![image](https://user-images.githubusercontent.com/17500430/131545959-dc9e5729-02ac-4515-8ed5-0bae50af2479.png)

**Comment by CAM-Gerlach** [comment]
Bump, still an issue :cry:

**Comment by nvuillam** [comment]
It should be solved by the yeoman-environment version, that I just upgraded in MegaLinter :)

Please can you try `npx mega-linter-runner@beta --install` ?

**Comment by CAM-Gerlach** [comment]
Hey @nvuillam , thanks again! Unfortunately, I still get what appears to be the same error. I'm not really familiar with the `npm` ecosystem; is it possible that an old version of `yeoman-environment` is still being cached, or I'm doing something else wrong?

Full output:

<details>

```
$ npx mega-linter-runner@beta --install
Need to install the following packages:
  mega-linter-runner@beta
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@npmcli/arborist@4.0.4',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || >=16' },
npm WARN EBADENGINE   current: { node: 'v15.0.1', npm: '7.21.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pacote@12.0.2',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || >=16' },
npm WARN EBADENGINE   current: { node: 'v15.0.1', npm: '7.21.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@npmcli/map-workspaces@2.0.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || >=16' },
npm WARN EBADENGINE   current: { node: 'v15.0.1', npm: '7.21.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@npmcli/metavuln-calculator@2.0.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || >=16' },
npm WARN EBADENGINE   current: { node: 'v15.0.1', npm: '7.21.0' }
npm WARN EBADENGINE }
Yeoman generator used: C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\generators\mega-linter
C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:749
        throw new Error(
              ^

Error: You don't seem to have a generator with the name “C:\Users\C.” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-C:\Users\C..

To see all your installed generators run yo --generators. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at checkGenerator (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:749:15)
    at Environment.create (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:776:29)
    at instantiateAndRun (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:987:36)
    at Environment.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:1004:12)
    at MegaLinterRunner.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\runner.js:50:11)
    at MegaLinterRunnerCli.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\cli.js:11:34)
    at C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\index.js:13:37
    at Object.<anonymous> (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
```

</details>

**Comment by nvuillam** [comment]
I already saw old versions used...

Try npm i mega-linter-runner@beta -g, then mega-linter-runner --install , and of it still does not work , it meabs that yeoman fix does not solve the pb :/

**Comment by CAM-Gerlach** [comment]
Nope, same error as before, in this case due to the space in the `Program Files` dirname (the default location for `npm install -g`), as occurred previously in this case.

<details>

```bash
$ mega-linter-runner --install
Yeoman generator used: C:\Program Files\nodejs\node_modules\mega-linter-runner\generators\mega-linter
C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:749
        throw new Error(
              ^

Error: You don't seem to have a generator with the name “C:\Program” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-C:\Program.

To see all your installed generators run yo --generators. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at checkGenerator (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:749:15)
    at Environment.create (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:776:29)
    at instantiateAndRun (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:987:36)
    at Environment.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:1004:12)
    at MegaLinterRunner.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\runner.js:50:11)
    at MegaLinterRunnerCli.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\cli.js:11:34)
    at C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\index.js:13:37
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
```

</details>

**Comment by nvuillam** [comment]
Mmmm the solution may be to separate install in another repo :/
Meanwhile you can manually install megalinter as described in documentation :/

**Comment by CAM-Gerlach** [comment]
Yeah, I though I mentioned it somewhere, but what I ended up doing was running it in a Linux VM, and then syncing the files over. Not exactly ideal, but not the end of the world.
